### ISSUE TITLE
PAINT_029 import image cancelation cleans canvas

### ISSUE THREAD

**Issue by cernoel** [sw19-tug/morning11#58]
*) taking a picture or importing an image.. and then cancel the import.. wipes the canvas

**Comment by Syrilus** [comment]
tested the bug in "commit 525de939ed49aa45ac756dc3ab07c7c3fbdb04b3" on the develop branch,

-> the described bug could not be reproduced
-> rather when importing the first image and then importing a second one, the second image replaces the first imported image.

**Comment by cernoel** [comment]
could reproduce it with camera import

**Comment by cernoel** [comment]
issue also got resolved, no issues on newer android release on huwaii phone
