### ISSUE TITLE
PAINT_030 App crash on tool use "Take picture"

### ISSUE THREAD

**Issue by Syrilus** [sw19-tug/morning11#61]
When starting the app and choosing the "Take picture" functionality from 
the tool palette the app crashes. 

-> crash log is attached 
->  it looks like there is a permission problem in android security which
causes the crash

![paintu_Bug](https://user-images.githubusercontent.com/34011017/59329457-32de1b80-8cef-11e9-88b4-789e7f0e8a6c.png)

**Comment by cernoel** [comment]
verified bug, first few tries there was "permission error" message, but i dont know what made it crash afterswards

**Comment by Syrilus** [comment]
We did some investigations into the bug, and removed "<uses-permission android:name="android.permission.CAMERA" /> " in the manifext xml file. 
according to: https://stackoverflow.com/questions/17010216/permission-denial-starting-intent?noredirect=1&lq=1

However on undoing the change, the app works as intended & the bug could not be reproduced thus far.
