### ISSUE TITLE
PAINT_034 filters sometimes apply only to imported images, not whole canvas

### ISSUE THREAD

**Issue by cernoel** [sw19-tug/morning11#69]
*) using filters after importing image, applies the filter only to the imported image
*) using filters in a row, makes some weird "restores old image" behaviour

**Comment by cernoel** [comment]
as seen in latest development version " Merge pull request #66 "

**Comment by cernoel** [comment]
issue PAINT_026 also fixed this issue as far is i could find out. please confirm and close!

**Comment by kochstef** [comment]
i have the problem that it apply's the filter only to the background.

**Comment by PavleGospavic** [comment]
Not sure if this is a problem with filters or with importing an image, since it happens to me when I import an image.

**Comment by kochstef** [comment]
I'm pretty sure it is because when you import it an make a draw action on the picture the filter works perfectly fine. I tried to draw the bitmap on the canvas after the import but it did not work for me but maybe I implemented it wrong because I think this may be a solution.

**Comment by cernoel** [comment]
latest tests on huaweii phone .. showed no issue.. so it works
