### ISSUE TITLE
PAINT_036 two taps needed to draw on the imported image

### ISSUE THREAD

**Issue by Syrilus** [sw19-tug/morning11#72]
when a new image gets imported and the "point" tool is chosen,
only 1 tap is needed to draw off-side of the imported image on the white canvas. 

however 

when you want to immediately draw on the imported image and tap on the image area itself
nothing happens, only upon the second tap an actual point gets drawn on the canvas !

(Probably is connected with other issues)

**Comment by cernoel** [comment]
issue got resolved with issue PAINT_026, please confirm and close issue!
